---


- hosts: all
  gather_facts: false
  remote_user: ubuntu
  become_user: root
  become_method: sudo


  tasks:
    - name: Install python 2
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)

    - name: Fancy way of doing authorized_keys
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup ('file', '~/.ssh/id_rsa.pub') }}"


  # - name: Create /root/.ssh
  #   file: path=/root/.ssh state=directory mode=0700
  # - name: Create /root/.ssh/authorized_keys from out local ssh pubkey
  #   lineinfile: dest=/root/.ssh/authorized_keys  line="{{ lookup('file', '~/,ssh/id_rsa.pub')}}"
